# Global
safe:									true
exclude:							[CNAME, LICENSE]
include:							[_pages]
timezone:							Europe/London

# Dependencies
markdown:							kramdown

# Styling
sass:
  sass_dir:						_sass
  style:							compressed

# Compression
compress_html:
  comments:						all
  clippings:					all

# Permalinks
permalink:						pretty

# Setup
title:                Scriptr
byline:								""
  
description:					"A web-based tool for Google Apps Scripts. Better editing, local storage, saving, diff'ing & committing to Github. Built atop of Ace for speed & ease of use."
url:									scriptr.space
baseurl:							/
author:
  name:								"Scriptr.space"
  url:								https://github.com/scriptr-space

# Custom variables
version:							"1.1.6"
launched:							"2016"
fonts:								"Anonymous+Pro:400|Inconsolata:400|Roboto:400,700|Roboto+Mono:400|Fira+Mono:400|Space+Mono:400"
production:           true

# Extras
analytics:
  enable:							true
  scroll:							false
  id:									"UA-53673057-7"

# API Keys
api_keys:
  google_general:			"AIzaSyDMHHexpu9ny_odFDPyoZT4eOpXYLsN13Q"
  google_oauth:				"906733969647-tsscu15blfumt6v8i79663stk8ggdn3t.apps.googleusercontent.com"
  github_oauth:       "770cdacd6fa33a1a269d"
  github_oauth_dev:   "0e6afe63555ffc47107b"