# Global
safe:									true
exclude:							[CNAME, LICENSE]
include:							[_pages]
timezone:							Europe/London

# Dependencies
markdown:							kramdown

# Styling
sass:
  sass_dir:						_sass
  style:							compressed

# Compression
compress_html:
  comments:						all
  clippings:					all

# Permalinks
permalink:						pretty

# Setup
title:                Scriptr
byline:								""
  
description:					""
url:									scriptr.space
baseurl:							/
author:
  name:								"Scriptr.space"
  url:								https://github.com/scriptr-space

# Custom variables
version:							"0.1.0"
launched:							"2016"
fonts:								"Anonymous+Pro:400|Inconsolata:400|Roboto:400,700|Roboto+Mono:400|Fira+Mono:400|Space+Mono:400"

# Extras
analytics:
  enable:							true
  id:									"UA-53673057-7"